site_name: ÁLGEBRA LINEAL - FAMAF UNC - Notas de Tomás Caruso
theme:
    name: material
    palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/weather-night
          name: Cambiar a modo oscuro
      - scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/white-balance-sunny
          name: Cambiar a modo claro
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  math:
    enable: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - roamlinks
